### ISSUE TITLE
Example Requests for Seamless

### ISSUE THREAD

**Issue by maythilr** [wirecard/wpp-integration-demo-php#24]
Hi,

Can we get some  example requests for Seamless Integration? Current examples shown are only for Standalone / Embedded only. We have been using the example requests for "Credit Card 3DS"  json for our seamless integration but that is not working too well. (Works with demo parameters but not with out UAT parameters). Wondering if we are missing something specific for seamless.

Thanks,
Ravi

**Comment by maythilr** [comment]
Current examples limited to standalone / embedded.
![Screen Shot 2019-07-08 at 10 28 31 pm](https://user-images.githubusercontent.com/51673974/60818851-0b388100-a1d1-11e9-8cbd-d4a4372b27d0.png)

**Comment by mke-wd** [comment]
Hi! 

Thanks for your input, maybe our documentation for Seamless WPP v2 helps? https://doc.wirecard.com/PPv2.html#WPP_Seamless

BR
Moritz

**Comment by MarkusHobisch** [comment]
Hi!

I don't know if you already have solved the problem with the seamless integration. For seamless solution there exists no requests because we use a different approach. You have to include the paymentPage.js into your html file. Then you can call seamlessRender and seamlessSubmit functions. SeamlessRender renders the payment page form and seamlessSubmit processes the payment. Please have a look at the seamless.php where we use the seamless solution. 

hth
Markus
